#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🧼 Cleanup...'
# yarn clean

echo '🏗️👷 Styling, testing your project before committing'

# Check ESLint Standards
yarn lint || (echo ' ❌ ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'; false;)

# Check Prettier standards
yarn check:format || (echo '❌ Prettier Check Failed. Run yarn format, add changes and try commit again.'; false;)

# Check TSconfig standards
yarn check:types || (echo '❌ Type Check Failed. Are you seriously trying to write that? Make the changes required above.'; false;)

# If everything passes... Now we can build
echo '🤔 ... Everything seems ok.'
